{{- if and .Values.image.username .Values.image.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" .  }}
{{- end }}
